(function (global) {
  "use strict";

  /**
   * 10 关：从地球到 M78，难度递增。
   * waves: 每波 { delayMs, spawns: [{ type, n }] }
   * boss: { key, name, hpMul, speedMul }
   */
  var LEVELS = [
    {
      id: 1,
      title: "第一关",
      subtitle: "地球 · 黎明出击",
      story: "赛罗与迪迦从地球出发，踏上拯救光之国的征途。",
      bgKey: "earth",
      waveCount: 2,
      spawnInterval: 2.1,
      gruntHp: 2,
      gruntSpeed: 55,
      bossKey: "redking",
      bossName: "骷髅怪兽 雷德王",
      bossHp: 80,
    },
    {
      id: 2,
      title: "第二关",
      subtitle: "月球 · 静海基地",
      story: "月面基地出现异次元裂缝，小型怪兽不断涌出。",
      bgKey: "moon",
      waveCount: 2,
      spawnInterval: 1.95,
      gruntHp: 2,
      gruntSpeed: 62,
      bossKey: "black",
      bossName: "恶劣宇宙人 美菲拉斯星人",
      bossHp: 100,
    },
    {
      id: 3,
      title: "第三关",
      subtitle: "火星 · 赤色荒原",
      story: "沙尘暴中潜伏着宇宙战斗兵器。",
      bgKey: "mars",
      waveCount: 3,
      spawnInterval: 1.85,
      gruntHp: 3,
      gruntSpeed: 68,
      bossKey: "golza",
      bossName: "超古代怪兽 哥尔赞",
      bossHp: 120,
    },
    {
      id: 4,
      title: "第四关",
      subtitle: "木星 · 大红斑轨道",
      story: "气态巨行星轨道上，帝国星人的舰队正在集结。",
      bgKey: "jupiter",
      waveCount: 3,
      spawnInterval: 1.75,
      gruntHp: 3,
      gruntSpeed: 74,
      bossKey: "temperor",
      bossName: "极恶宇宙人 帝国星人",
      bossHp: 145,
    },
    {
      id: 5,
      title: "第五关",
      subtitle: "土星 · 光环碎片区",
      story: "冰晶与岩石碎片中，巴尔坦星人的分身术令人眼花缭乱。",
      bgKey: "saturn",
      waveCount: 3,
      spawnInterval: 1.65,
      gruntHp: 4,
      gruntSpeed: 78,
      bossKey: "baltan",
      bossName: "宇宙忍者 巴尔坦星人",
      bossHp: 165,
    },
    {
      id: 6,
      title: "第六关",
      subtitle: "天王星 · 极寒云顶",
      story: "极低温云层里，冷冻怪兽波贡苏醒。",
      bgKey: "uranus",
      waveCount: 4,
      spawnInterval: 1.55,
      gruntHp: 4,
      gruntSpeed: 82,
      bossKey: "bogun",
      bossName: "冷冻怪兽 波贡",
      bossHp: 185,
    },
    {
      id: 7,
      title: "第七关",
      subtitle: "海王星 · 深蓝风暴",
      story: "巨型风暴眼中心，梅特龙星人布下精神干扰网。",
      bgKey: "neptune",
      waveCount: 4,
      spawnInterval: 1.45,
      gruntHp: 5,
      gruntSpeed: 86,
      bossKey: "metron",
      bossName: "幻觉宇宙人 梅特龙星人",
      bossHp: 205,
    },
    {
      id: 8,
      title: "第八关",
      subtitle: "冥王星 · 边境前哨",
      story: "太阳系边缘，古维拉与双头怪兽庞敦联手拦路。",
      bgKey: "pluto",
      waveCount: 4,
      spawnInterval: 1.35,
      gruntHp: 5,
      gruntSpeed: 90,
      bossKey: "twin",
      bossName: "双头怪兽 庞敦",
      bossHp: 230,
    },
    {
      id: 9,
      title: "第九关",
      subtitle: "M78 轨道 · 光之国门前",
      story: "家园已在眼前，安培拉星人的黑暗波动笼罩轨道站。",
      bgKey: "m78orbit",
      waveCount: 5,
      spawnInterval: 1.25,
      gruntHp: 6,
      gruntSpeed: 95,
      bossKey: "emperor",
      bossName: "黑暗宇宙大皇帝 安培拉星人",
      bossHp: 280,
    },
    {
      id: 10,
      title: "最终关",
      subtitle: "光之国 · 贝利亚之乱",
      story: "邪恶贝利亚企图吞噬等离子火花塔，决战在此一举！",
      bgKey: "m78",
      waveCount: 5,
      spawnInterval: 1.15,
      gruntHp: 7,
      gruntSpeed: 100,
      bossKey: "belial",
      bossName: "邪恶贝利亚",
      bossHp: 420,
    },
  ];

  global.LevelData = { LEVELS };
})(typeof window !== "undefined" ? window : globalThis);
